package com.stone.orm;

import com.stone.orm.Emp;
import com.stone.orm.EmpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HR.EMP
	 * @mbg.generated  Tue Nov 20 11:13:51 CST 2018
	 */
	int insert(Emp record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table HR.EMP
	 * @mbg.generated  Tue Nov 20 11:13:51 CST 2018
	 */
	int insertSelective(Emp record);
}